"""
inferfabric/interfaces.py — Protocol abstract layer for dependency injection.

P3 of v4.1 optimization: structural typing via typing.Protocol.
Runtime zero-overhead (no registration, no ABC subclasses).

Each Protocol maps to a concrete implementation:
  IStateDB          → StateDB (state.py)
  IProcessManager  → ProcessManager (process_manager.py)
  IHealthChecker   → ModelManager health methods (manager.py)
  IGPULock         → GPULock (gpu_lock.py)
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


# ─── State Database ─────────────────────────────────────────────

@runtime_checkable
class IStateDB(Protocol):
    """SQLite-backed state store.

    Concrete: StateDB (state.py)
    """

    def get(self, key: str) -> str | None: ...
    def set(self, key: str, value: str) -> None: ...
    def set_multi(self, kv: dict[str, str]) -> None: ...

    def get_active_services(self) -> list[str]: ...
    def set_active_services(self, services: list[str]) -> None: ...
    def add_active_service(self, name: str) -> None: ...
    def remove_active_service(self, name: str) -> None: ...

    def record_manual_stop(self, name: str) -> None: ...
    def is_manually_stopped(self, name: str) -> bool: ...
    def clear_manual_stop(self, name: str) -> None: ...

    def get_sleep_state(self, model_name: str) -> str | None: ...
    def set_sleep_state(self, model_name: str, level: int | None) -> None: ...
    def get_all_sleep_states(self) -> dict[str, str]: ...

    def add_history(
        self,
        from_profile: str,
        to_profile: str,
        duration: float,
        status: str = "ok",
    ) -> None: ...
    def get_history(self, limit: int = 20) -> list[dict]: ...

    @property
    def gpu_mode(self) -> str: ...
    @gpu_mode.setter
    def gpu_mode(self, mode: str) -> None: ...


# ─── Process Manager ────────────────────────────────────────────

@runtime_checkable
class IProcessManager(Protocol):
    """Unified process lifecycle for vLLM, ComfyUI, Ollama.

    Concrete: ProcessManager (process_manager.py)
    """

    @property
    def vllm_pid(self) -> int | None: ...
    @property
    def comfyui_pid(self) -> int | None: ...

    def start_vllm(self, cfg: "VLLMConfig", model_type: str = "") -> dict: ...
    def stop_vllm(self, port: int | None = None) -> dict: ...

    def start_comfyui(self, cfg: "ComfyUIConfig") -> dict: ...
    def stop_comfyui(self, port: int | None = None) -> dict: ...
    def stop_comfyui_with_config(
        self, cfg: "ComfyUIConfig", port: int | None = None
    ) -> dict: ...

    def start_ollama_cpp(self, cfg: "OllamaCppConfig") -> dict: ...
    def stop_ollama_cpp(self, port: int | None = None) -> None: ...

    def run_ollama(
        self, model_ref: str, keep_alive: str = "5m", num_gpu: int = -1
    ) -> dict: ...

    def stop_all(
        self,
        comfyui_cfg: "ComfyUIConfig | None" = None,
        vllm_ports: list[int] | None = None,
        comfyui_port: int | None = None,
    ) -> dict: ...
    def force_kill_all(self) -> dict: ...

    def sleep_vllm(self, port: int) -> dict: ...
    def wake_vllm(self, port: int) -> dict: ...
    def is_vllm_alive(self, port: int) -> bool: ...
    def is_comfyui_alive(self, port: int = 8188) -> bool: ...


# ─── Health Checker ─────────────────────────────────────────────

@runtime_checkable
class IHealthChecker(Protocol):
    """Model and GPU health probing.

    Concrete: ModelManager health methods (manager.py) act as default.
    """

    def check(self, url: str, timeout: int = 3) -> str: ...
    def wait(self, url: str, timeout: int = 300) -> bool: ...
    def gpu_used_mb(self) -> int: ...


# ─── GPU Lock ───────────────────────────────────────────────────

@runtime_checkable
class IGPULock(Protocol):
    """GPU mutual exclusion via flock.

    Concrete: GPULock (gpu_lock.py)
    """

    @property
    def is_held(self) -> bool: ...
    def acquire(self, timeout: float = 0) -> bool: ...
    def release(self) -> None: ...
    def force_clear(self) -> None: ...